### ISSUE TITLE
Patch for ARI regarding .cloud

### ISSUE THREAD

**Issue by incubatec** [thedarkwinter/Net-DRI#107]
diff -rwib Net-DRI-master/lib/Net/DRI/DRD/ARI.pm /usr/local/share/perl/5.18.2/Net/DRI/DRD/ARI.pm
107,108c107,108
<  my @uncontented = qw/xn--ngbc5azd xn--ngbrx abudhabi arab build dubai host krd luxury melbourne men menu physio press space sydney website/;
<  my @contended = qw/xn--hxt814e xn--5tzm5g app baby band bank blog box chat city click ***cloud*** cpa deals design doctor eco film home hosting hotel inc insurance law love movie music news now online ping rip salon secure sex shop site soccer spa sport spot store studio style sucks tennis web world /;
---
>  my @uncontented = qw/xn--ngbc5azd xn--ngbrx abudhabi arab build dubai host krd luxury melbourne men menu physio press space sydney website ***cloud***/;
>  my @contended = qw/xn--hxt814e xn--5tzm5g app baby band bank blog box chat city click cpa deals design doctor eco film home hosting hotel inc insurance law love movie music news now online ping rip salon secure sex shop site soccer spa sport spot store studio style sucks tennis web world /;

Also the string cloud needs to be added to:
Net-DRI-master/lib/Net/DRI/DRD/NGTLD.pm
two times (new wef, one time as cloud the other as array element 'cloud').

**Comment by thedarkwinter** [comment]
Thanks for the patch, I have updated [here](https://github.com/thedarkwinter/Net-DRI/commit/2683f2027437f2c5ac556c9f1d543429c82c44fe)
