### ISSUE TITLE
AFNIC upcoming Host Object changes

### ISSUE THREAD

**Issue by incubatec** [thedarkwinter/Net-DRI#298]
Please see the attached file:
[Technical-specifications-objet-host-EN.pdf](https://github.com/thedarkwinter/Net-DRI/files/2302476/Technical-specifications-objet-host-EN.pdf)

**Comment by thedarkwinter** [comment]
Thanks. Should just be a matter of changing [this](https://github.com/thedarkwinter/Net-DRI/blob/master/lib/Net/DRI/DRD/AFNIC/AFNIC.pm#L73), but will test on the sandbox in October/Earliy November.

**Comment by thedarkwinter** [comment]
This was done in this commit https://github.com/thedarkwinter/Net-DRI/commit/5c24e3c8aba305aadddeaa155325cf4841768882#diff-bc6dd71154164dce81da8853d425e9ad7edcc63943b389c18d4182ae8187ce81 but I never closed this Issue. Sorted :+1:
