### ISSUE TITLE
VeriSign::NameStore Contact Creation Fails

### ISSUE THREAD

**Issue by incubatec** [thedarkwinter/Net-DRI#322]
When trying to create a contact for .NAME domain registrations using the VeriSign::NameStore module, the following error is given via EPP:

`<?xml version="1.0" encoding="UTF-8"?><epp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd" xmlns="urn:ietf:params:xml:ns:epp-1.0"><response><result code="2306"><msg>Parameter value policy error</msg><extValue><value xmlns:epp="urn:ietf:params:xml:ns:epp-1.0"><epp:undef/></value><reason>Service: DOTCOM not found</reason></extValue></result><trID><clTRID>VERISIGN::NAMESTORE-8882-1549037835544049</clTRID><svTRID>1549037835614-620386828</svTRID></trID></response></epp>`

The request XML is created as follows by Net::DRI:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd"><command><create><contact:create xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xsi:schemaLocation="urn:ietf:params:xml:ns:contact-1.0 contact-1.0.xsd"><contact:id>123</contact:id><contact:postalInfo type="loc"><contact:name>John Doe</contact:name><contact:org>Megaorg</contact:org><contact:addr><contact:street>Via Marte 11</contact:street><contact:street/><contact:street/><contact:city>Borgo Fantasia</contact:city><contact:sp>BZ</contact:sp><contact:pc>39100</contact:pc><contact:cc>IT</contact:cc></contact:addr></contact:postalInfo><contact:voice>+39.0123456789</contact:voice><contact:email>blackhole@blackhole.cloud</contact:email><contact:authInfo><contact:pw>S0M3R@Nd0MPwD</contact:pw></contact:authInfo></contact:create></create><extension><namestoreExt:namestoreExt xmlns:namestoreExt="http://www.verisign-grs.com/epp/namestoreExt-1.1" xsi:schemaLocation="http://www.verisign-grs.com/epp/namestoreExt-1.1 namestoreExt-1.1.xsd"><namestoreExt:subProduct>dotCOM</namestoreExt:subProduct></namestoreExt:namestoreExt></extension><clTRID>VERISIGN::NAMESTORE-8882-1549037835544049</clTRID></command></epp>`

The problem is that it should not automatically specifcy "dotCOM" as sub-product:
`<namestoreExt:subProduct>dotCOM</namestoreExt:subProduct>`
and instead use
`<namestoreExt:subProduct>dotNAME</namestoreExt:subProduct>`
to get the correct results. This can be achieved by forcing the $ext variable in _Net/DRI/Protocol/EPP/Extensions/VeriSign/NameStore.pm_ to "name", but that probably will cause issues e.g. for .COM domains thereafter.

Any ideas on how to solve this without completely separating the extensions?

**Comment by thedarkwinter** [comment]
Yes, this is very fidgety!

Have you tried specifying the subproductid like [this](https://github.com/thedarkwinter/Net-DRI/blob/master/t/Net/DRI/Protocol/EPP/Extensions/VeriSign/JobsContact.t#L97)
$rc = $dri->contact_create($c, {subproductid => 'dotAA'});

Alternatively, in your code, you can switch the current_product manually in your logic.

```
// add profile with namestore extension and set to auto (which will auto switch if it can detect from the TLD e.g. in a domain comman
$dri->add_current_profile('main','epp',{},{default_product=>'_auto_',extensions=>['VeriSign::NameStore']});

// if you want to create a contact, you can manually set the current_product
// old tlds use proceeding dot, but I think this is/has changed to remove dot in some TLDs
if ( $target_tld =~ m/\.(com|net|cc|tv|bz|jobs|name)$/ ) { // original TLDs
    $self->protocol()->{current_product} = 'dot' . uc $1;
} elsif ( $target_tld =~ m/\.(.*)$/ ) { // new gTLDs
    $self->protocol()->{current_product} = uc $1;
}

// now you don't need to specify subproductid in any commands
$rc = $dri->contact_create($c);
```

I realize this might be a bit late, but I hope it helps

**Comment by thedarkwinter** [comment]
As there isn't really a solution to this, the above example hopefully explains it a little, but I will close this isse.
