### ISSUE TITLE
Eurid epp change

### ISSUE THREAD

**Issue by frankcom** [thedarkwinter/Net-DRI#375]
Hi, is it planned to add the new Eurid epp changes in April?
Regards

**Comment by thedarkwinter** [comment]
I believe paulo is looking at this, so will hopefully have the changes first week of april

**Comment by thedarkwinter** [comment]
Changes are in https://github.com/thedarkwinter/Net-DRI/pull/378 but the registry has delayed the update

**Comment by sasa-mladenovic-troxo** [comment]
@thedarkwinter  Do you know until when the registry delayed this update?

**Comment by frankcom** [comment]
Hi, according to Registrar Web there is the following information:
We would like to inform you that due to the challenging times and following the feedback from the Registrar Advisory Board, we have decided to postpone our code-breaking release (originally planned for 8 April 2020), until further notice.

You will be informed as soon as we have confirmed a new date.

In the meantime, the Staging environment will remain available so you can test the planned changes at your own convenience.

Please note, we will use the previously scheduled maintenance downtime on 8 April for an internal maintenance, with no changes to the registration system.

    Date: 8 April 2020
    Production maintenance window and downtime: 06:00-09:00 CEST
    Codebreaking: No
    Service Interruption: EPP, Registrar Extranet

Should you have any questions, please contact your Liaison Manager

**Comment by frankcom** [comment]
Just for information:
Our code-breaking release (originally planned for 8 April 2020) will take place on Wednesday, 17 June 2020.

**Comment by thedarkwinter** [comment]
This has been merged now.
