### ISSUE TITLE
Question about updating

### ISSUE THREAD

**Issue by frankcom** [thedarkwinter/Net-DRI#382]
Can anybody assist me, what is the best way to update to new version, when changes are made?
Would it be enough for example to upload the new "Eurid" files, when epp changes are done?
Regards hope all is ok with you

**Comment by thedarkwinter** [comment]
Hi @frankcom. As I am not 100% clear on your question, I will answer twice.

1) If you're developing changes, I would appreciate any contributions. They best way would be to fork and pull request against the master branch. That said, if you plan to do any development, it might be worth giving me a shout beforehand in case its already being done elsewhere. In the case of EurID, I have a pull request waiting from Paulo [here](https://github.com/thedarkwinter/Net-DRI/pull/378) for the now delayed April release. Is this what you were talking about?

2) If you are only referring to installing updates from this repository, it should be sufficient for you to pull the latest master branch. While this is essentially a "non stable no guarantees" repository, it will likely always be.  The master branch is used in production with multiple registries, so it is more or less stable, and fixed quickly when there are issues. The dynamic nature of it means we can add support and updates for registries quickly.
- If you want to only uplaod new Eurid files, I would say that should not be a problem, just remember to add the test files too, and run all tests by executing `prove -r -Ilib t/`
- Caveat, if you are currently using Net-DRI from metacpan, you will find that we have diverged greatly, so only copying Eurid files might or might not work.

Hope this helps.

**Comment by frankcom** [comment]
Hello and sorry for the confusion :)
Many thanks for your detailed answer. 
I am not the programmer guy - much more the user.
I am currently using Net-DRI (self downloaded - not by metacpan) for the basics of Eurid like checking, updating or registering domains.
My question is specially asked, what to do when Eurid changes things in system, so it seems that answer 2 would fit fine. 
As I am running the systems on different servers I have asked for the most convenient way to update.
Thanks for doing such great work to all of you.
