### ISSUE TITLE
DeNIC use ssl

### ISSUE THREAD

**Issue by ivan1986** [thedarkwinter/Net-DRI#387]
Net/DRI/DRD/DENIC.pm:93

socktype=>'ssl'

not 

socktype=>'tcp'

testing 08.06.2020 - on tcp can not connect, on ssl works fine

**Comment by thedarkwinter** [comment]
Thanks I will have a look when I get a mo. (client code can override the default, which is why I missed this before)

**Comment by thedarkwinter** [comment]
This is now commited here.
Thanks for the tip @ivan1986
