### ISSUE TITLE
Question about error with Eurid

### ISSUE THREAD

**Issue by frankcom** [thedarkwinter/Net-DRI#389]
Hello,
I am using the following method for bulk checking domains:

I put all combinations from aaa-zzz in different txt files with 359 lines each and run a batch check with domain_check ./filecontaininglist.txt

For the 3 letter it works great :-)

For the 2 letter from aa-zz I tried the same, but it is not running through, because it stops with "ad.eu" Invalid domain name (error NAME_WITH_COUNTRY_CODE).

I know that some names are blocked by registry of course, but would there be a way just to skip this error or do I have to check all names manually by hand and remove them from the list file?

Kind regards and thanks
Frank

**Comment by thedarkwinter** [comment]
Hi Frank

If you set this "no_country_code" to zero it should disable that check.
https://github.com/thedarkwinter/Net-DRI/blob/master/lib/Net/DRI/DRD/EURid.pm#L119

I assume Eurid blocks country code registrations, so they wouldn't be valid, but the script should at least work.

Hope this helps (and I'm not too late). Let me know how it goes...

Cheers,
Michael

**Comment by frankcom** [comment]
Many thanks this solution works perfect! :-) Great support!
