### ISSUE TITLE
Any function to "keep connection alive"?

### ISSUE THREAD

**Issue by frankcom** [thedarkwinter/Net-DRI#501]
Hello,
I am aware of the fact that you are not working anymore on NetDRI, but hopefully you can give me an information, if there is the function integrated to keep connections to registries alive. It could be done by sending a poll or "hello" command e.g..
Maybe it is already integrated and I do not need to do it manually?
Best regards and many thanks
Frank

**Comment by thedarkwinter** [comment]
Hi @frankcom 
No there was nothing built in from memory as it would likely creating a blocking scenario, so it needs to be added manually - so you can trigger a logout to end session, or a hello every x minutes depending on your wait mechanism if you are keeping connection alive.
Have a nice day :)
Michael

**Comment by frankcom** [comment]
Hi Michael, thanks for your quick reply, I highly appreciate this. I will now check if there is immediate disconnect after sending a command e.g. domain_check after each command or if there is a bit time with same connection open. The best for now!
